{
 "title": "Visitors",
 "tags": [
  "lab",
  "visitors"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "External visits (selected range)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"lab\", app=\"doom-dashboard\", container=\"nginx\"} |= \"HTTP/\" != \"kube-probe\" != \"Uptime-Kuma\" | pattern `<ip> - - [<_>] \"<method> <path> <_>\" <status> <_>` | ip !~ `10\\..+` | ip !~ `172\\.(1[6-9]|2[0-9]|3[01])\\..+` | ip !~ `192\\.168\\..+` | ip !~ `127\\..+` | ip !~ `169\\.254\\..+` [$__range]))"
    }
   ]
  },
  {
   "title": "Visits over time",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 6 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"lab\", app=\"doom-dashboard\", container=\"nginx\"} |= \"HTTP/\" != \"kube-probe\" != \"Uptime-Kuma\" | pattern `<ip> - - [<_>] \"<method> <path> <_>\" <status> <_>` | ip !~ `10\\..+` | ip !~ `172\\.(1[6-9]|2[0-9]|3[01])\\..+` | ip !~ `192\\.168\\..+` | ip !~ `127\\..+` | ip !~ `169\\.254\\..+` [$__interval]))"
    }
   ]
  },
  {
   "title": "Top visitor IPs",
   "type": "table",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 11 },
   "targets": [
    {
     "expr": "topk(25, sum by (ip) (count_over_time({namespace=\"lab\", app=\"doom-dashboard\", container=\"nginx\"} |= \"HTTP/\" != \"kube-probe\" != \"Uptime-Kuma\" | pattern `<ip> - - [<_>] \"<method> <path> <_>\" <status> <_>` | ip !~ `10\\..+` | ip !~ `172\\.(1[6-9]|2[0-9]|3[01])\\..+` | ip !~ `192\\.168\\..+` | ip !~ `127\\..+` | ip !~ `169\\.254\\..+` [$__range])))"
    }
   ]
  },
  {
   "title": "Top paths",
   "type": "table",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 11 },
   "targets": [
    {
     "expr": "topk(15, sum by (path) (count_over_time({namespace=\"lab\", app=\"doom-dashboard\", container=\"nginx\"} |= \"HTTP/\" != \"kube-probe\" != \"Uptime-Kuma\" | pattern `<ip> - - [<_>] \"<method> <path> <_>\" <status> <_>` | ip !~ `10\\..+` | ip !~ `172\\.(1[6-9]|2[0-9]|3[01])\\..+` | ip !~ `192\\.168\\..+` | ip !~ `127\\..+` | ip !~ `169\\.254\\..+` [$__range])))"
    }
   ]
  },
  {
   "title": "Recent visitor requests",
   "type": "logs",
   "gridPos": { "x": 0, "y": 17, "w": 24, "h": 13 },
   "targets": [
    {
     "expr": "{namespace=\"lab\", app=\"doom-dashboard\", container=\"nginx\"} |= \"HTTP/\" != \"kube-probe\" != \"Uptime-Kuma\" | pattern `<ip> - - [<_>] \"<method> <path> <_>\" <status> <_>` | ip !~ `10\\..+` | ip !~ `172\\.(1[6-9]|2[0-9]|3[01])\\..+` | ip !~ `192\\.168\\..+` | ip !~ `127\\..+` | ip !~ `169\\.254\\..+`"
    }
   ]
  }
 ]
}