apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-fabric-metrics
  namespace: nginx-gateway
  labels:
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: nginx-gateway-fabric
spec:
  selector:
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: nginx-gateway-fabric
  ports:
  - name: metrics
    port: 9113
    targetPort: 9113
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway-fabric
      app.kubernetes.io/instance: nginx-gateway-fabric
  namespaceSelector:
    matchNames:
    - nginx-gateway
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
